### ISSUE TITLE
Error deploying last version

### ISSUE THREAD

**Issue by NastuzziSamy** [swoole/docker-swoole#29]
Hi, thank you for this docker image.

I deploy my Laravel application on Google Run, and I used to use the last version `phpswoole/swoole:php8.0-alpine` which happened to work until this month.

Everytime I build my app with this image, from yesterday, I got 503 page.

Now I use the previous version `phpswoole/swoole:4.7-php8.0-alpine` and it works perfectly, like before.

Hashes:
Last versions:
`sha256:a86d09eba2941db0e6a8424086b7012133f7a43626f00fd14667ab6ca4c302b6`: doesnt work
`sha256:4d43d47178801ff1dbbeb2230e59547a138f50c5a631951a841678de4106b484`: works (31 oct)

4.7:
`sha256:8f6cb15d6c0b2ae79ddf51c61d09fb4c70126794ff1cc4e500d4478a8ca03ac1`: works

Thank you

**Comment by sy-records** [comment]
Thank you for your feedback. 

`phpswoole/swoole:php8.0-alpine` is built using the `master` branch of `swoole-src`, so you may run into bugs because it is a development branch.

It is recommended that you use an image based on a stable version  

https://github.com/swoole/docker-swoole#versioned-images-based-on-stable-releases-of-swoole
